### ISSUE TITLE
question about vl_svmtrain

### ISSUE THREAD

**Issue by 20155004** [cvpa3/pa3#10]
Same as vl_simplenn
how to use it?? 

오류 발생: trainBinarySvm (line 36)
  [w, b] =  vl_svmtrain(idx2desc,cid,lambda, [],epsilon,10/lambda, biasMultiplier,  biasLearningRate,[], loss, solver);

there are so many options..

**Comment by Jinwoo-Jeon** [comment]
when using vl_svmtrain with learning parameters, you should use with 'parameter name' and parameter value like

> [w, b] = vl_svmtrain(x, y, lambda, 'epsilon', epsilon, ...
>     'biasMultiplier', biasMultiplier, 'biasLearningRate', biasLearningRate, 'loss', loss, 'solver', solver);

**Comment by wonyJ** [comment]
(20153584)
Also, second parameter 'y' is a vector of binary label(If each data has same class id with cid, then label is 1. Else, label is -1).

**Comment by 20155004** [comment]
So we need 67times svmtrain for each class. right?

**Comment by Jinwoo-Jeon** [comment]
Yes
