### ISSUE TITLE
Is there anyone who can help me with vl_nnconv error?

### ISSUE THREAD

**Issue by Jinwoo-Jeon** [cvpa3/pa3#6]
When I tried

> vl_simplenn(net,im)

I encountered this error

> Error using vl_nnconv
> An input is not a SINGLE array nor it is empty.
> 
> Error in vl_simplenn (line 193)
>         res(i+1).x = vl_nnconv(res(i).x, l.weights{1},
>         l.weights{2}, ...

input val im is an array with size 224x224x3
Anyone have an idea?

**Comment by BAILOOL** [comment]
You need to make the image single. You can make it by im = single(im);

**Comment by Jinwoo-Jeon** [comment]
@BAILOOL Oh.. I couldn't get what single means there.. Thanks!
